### ISSUE TITLE
有详细的语法规范吗

### ISSUE THREAD

**Issue by snylonue** [bangumi/wiki-syntax-spec#1]
目前正在写[解析器](https://github.com/snylonue/bgm-wiki-parser)，只能根据测试用例猜测

**Comment by trim21** [comment]
暂时还没有，因为没法对应修改旧主站的代码，所以也没啥动力写。

考虑下写一个PR一下？

**Comment by snylonue** [comment]
> 考虑下写一个PR一下？

以前没写过，如果不介意的话可以试着写下

不过感觉测试用例需要改下，有一些大小写错误
另外问下解析器一定能要输出和测试用例一样的 yaml  文件吗

**Comment by trim21** [comment]
> 另外问下解析器一定能要输出和测试用例一样的 yaml 文件吗

同名的 yaml 文件是用来描述 wiki 解析结果的，json 不能写注释就用 yaml 了，毕竟 yaml 解析器一抓一大把。

**Comment by trim21** [comment]
> 不过感觉测试用例需要改下，有一些大小写错误

有些 yaml 文件里的 `value` 也应该改下，现在混着有string和array两种类型，有些语言用解析起来挺麻烦的。

**Comment by snylonue** [comment]
> > 不过感觉测试用例需要改下，有一些大小写错误
> 
> 有些 yaml 文件里的 `value` 也应该改下，现在混着有string和array两种类型，有些语言用解析起来挺麻烦的。

还有`data`下面的`null`换成空字符串会比较方便

**Comment by trim21** [comment]
稍微写了几条

**Comment by trim21** [comment]
rust写的话似乎可以编译成wasm和pyo3前后端通用了 b38
